# 9.	Assignment on Multi classification using Multilayer Perceptron (MLP):  Buid an application to classify a given flower into its specie using MLP. Use Iris dataset from Kaggle. Display Accuracy score, Classification report and Confusion matrix.

In [1]:
# Importing Dependencies
import sklearn
import pandas as pd    # data processing, CSV file I/O (e.g. pd.read_csv)
import numpy as np     # linear algebra

In [2]:
#load the Iris flower dataset, which is in the "../input/" directory
dataset=pd.read_csv('iris.csv')     # the iris dataset is now a Pandas DataFrame

In [3]:
# first five observations
dataset.head()

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [4]:
# Number of observations and missing values. 
# There are 150 observations and no nan value
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   Id             150 non-null    int64  
 1   SepalLengthCm  150 non-null    float64
 2   SepalWidthCm   150 non-null    float64
 3   PetalLengthCm  150 non-null    float64
 4   PetalWidthCm   150 non-null    float64
 5   Species        150 non-null    object 
dtypes: float64(4), int64(1), object(1)
memory usage: 7.2+ KB


In [5]:
#Recreate the dataset with the help of existing attributes of the dataset
x=dataset[['SepalLengthCm','SepalWidthCm','PetalLengthCm','PetalWidthCm']]
y = dataset[['Species']].replace(['Iris-setosa','Iris-versicolor','Iris-virginica'],[0,1,2])

df = pd.concat([x, y], axis=1)
df.sample(n=5)

SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  Species
72             6.3           2.5            4.9           1.5        1
134            6.1           2.6            5.6           1.4        2
17             5.1           3.5            1.4           0.3        0
60             5.0           2.0            3.5           1.0        1
136            6.3           3.4            5.6           2.4        2

In [6]:
# Split data into a training set and a testing set.
# train_test_split shuffle the data before the split (shuffle=True by default)
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.3,random_state=1)

#Standardising the training data
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()
scaler.fit(X_train)

X_train=scaler.transform(X_train)
X_test=scaler.transform(X_test)

In [7]:
#Building the model with the help of Multi Layered Classifier
from sklearn.neural_network import MLPClassifier

In [8]:
clf = MLPClassifier(hidden_layer_sizes=(10, 10,10), max_iter=1000)      # create a classifier object


In [9]:
clf.fit(X_train, y_train.values.ravel())     # fit the classifier with X and Y data 

MLPClassifier(hidden_layer_sizes=(10, 10, 10), max_iter=1000)

In [10]:
# Now get predictions from the model and create a confusion matrix and a classification report.
y_pred = clf.predict(X_test)

In [11]:
# Model Accuracy, how often is the classifier correct?
from sklearn.metrics import accuracy_score
print('Accuracy Score : ',accuracy_score(y_test, y_pred))

Accuracy Score :  0.9555555555555556


In [12]:
#Generate the classification report
from sklearn.metrics import classification_report
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        14
           1       0.94      0.94      0.94        18
           2       0.92      0.92      0.92        13

    accuracy                           0.96        45
   macro avg       0.96      0.96      0.96        45
weighted avg       0.96      0.96      0.96        45



In [13]:
#Find the confusion matrrix
from sklearn.metrics import confusion_matrix
print(confusion_matrix(y_test, y_pred))

[[14  0  0]
 [ 0 17  1]
 [ 0  1 12]]
